services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/deeverse.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - jenkins-home:/mnt/jenkins_home
      - jenkins-temp:/mnt/jenkins_temp
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    networks:
      - deeverse_proxy

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx_reload.sh:/etc/letsencrypt/deploy_hook/nginx_reload.sh
    ## First run: certonly --webroot -w /var/www/certbot -d dees.kr -d www.dees.kr --non-interactive --agree-tos --email tunacome@gmail.com 
    ## This is for running the stack all-time
    # entrypoint: >
    #   /bin/sh -c 'trap exit TERM;
    #   while :; do
    #     certbot renew --webroot -w /var/www/certbot \
    #     --deploy-hook "/SCRIPT/PATH";
    #     sleep 1;
    #   done'
    ## For on-off stack, which happens to be my case
    entrypoint: >
      /bin/sh -c 'certbot renew --webroot -w /var/www/certbot
      --deploy-hook /etc/letsencrypt/deploy_hook/nginx_reload.sh'
    networks:
      - deeverse_proxy
    depends_on:
      - nginx

volumes:
  jenkins-home:
    external: true
  jenkins-temp:
    external: true

networks:
  deeverse_proxy:
    external: true
